"use client";

import { useCallback, useEffect, useState } from "react";
import { UploadDropzone } from "@/lib/uploadthing-client";

type Image = { url: string; uploadKey?: string | null; alt?: string | null; position: number };
type Variant = { name: string; price: number; compareAtPrice?: number | null; sku?: string | null; position: number };
type Product = { id: number; name: string; slug: string; sku: string | null; unitLabel: string | null; price: number; compareAtPrice: number | null; shortDescription: string | null; description: string | null; usageGuide: string | null; preservationGuide: string | null; stockStatus: string; status: string; isFeatured: boolean; isOnSale: boolean; isBestSeller: boolean; isNew: boolean; images: Image[]; variants: Variant[]; categories: { id: number; name: string }[] };
type Category = { id: number; name: string }; type Meta = { page: number; pageCount: number; total: number; pageSize: number };
const empty = { name: "", slug: "", sku: "", unitLabel: "", price: 0, compareAtPrice: "", shortDescription: "", description: "", usageGuide: "", preservationGuide: "", stockStatus: "in_stock", status: "active", isFeatured: false, isOnSale: false, isBestSeller: false, isNew: false, categoryIds: [] as number[], images: [] as Image[], variants: [] as Variant[] };
const field = "w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-shop-main";

export function ProductManager() {
    const [items, setItems] = useState<Product[]>([]), [categories, setCategories] = useState<Category[]>([]), [meta, setMeta] = useState<Meta>({ page: 1, pageCount: 1, total: 0, pageSize: 10 }); const [search, setSearch] = useState(""), [sort, setSort] = useState("createdAt"), [direction, setDirection] = useState("desc"), [form, setForm] = useState(empty), [editing, setEditing] = useState<number | null>(null), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
    const load = useCallback(async (page = 1) => { const x = await fetch(`/api/admin/products?page=${page}&search=${encodeURIComponent(search)}&sort=${sort}&direction=${direction}`).then(r => r.json()); setItems(x.data ?? []); setMeta(x.pagination ?? meta) }, [search, sort, direction]);
    useEffect(() => { void load(); fetch("/api/admin/categories/options").then(r => r.json()).then(x => setCategories(x.data ?? [])) }, [load]);
    function edit(p: Product) { setEditing(p.id); setForm({ ...empty, ...p, sku: p.sku ?? "", unitLabel: p.unitLabel ?? "", compareAtPrice: p.compareAtPrice?.toString() ?? "", shortDescription: p.shortDescription ?? "", description: p.description ?? "", usageGuide: p.usageGuide ?? "", preservationGuide: p.preservationGuide ?? "", categoryIds: p.categories.map(c => c.id) }); scrollTo({ top: 0, behavior: "smooth" }) }
    async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setMessage(""); const body = { ...form, price: Number(form.price), compareAtPrice: form.compareAtPrice === "" ? null : Number(form.compareAtPrice), sku: form.sku || null, unitLabel: form.unitLabel || null, shortDescription: form.shortDescription || null, description: form.description || null, usageGuide: form.usageGuide || null, preservationGuide: form.preservationGuide || null }; const r = await fetch(editing ? `/api/admin/products/${editing}` : "/api/admin/products", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const x = await r.json(); setBusy(false); if (!r.ok) return setMessage(x.error ?? "Có lỗi xảy ra."); setForm(empty); setEditing(null); setMessage("Đã lưu sản phẩm."); await load() }
    async function remove(id: number) { if (!confirm("Xóa sản phẩm và toàn bộ biến thể, hình ảnh?")) return; const r = await fetch(`/api/admin/products/${id}`, { method: "DELETE" }); const x = await r.json(); if (!r.ok) return setMessage(x.error); await load() }
    const set = (key: string, value: unknown) => setForm(f => ({ ...f, [key]: value }));
    return <div className="space-y-6"><header><h1 className="text-2xl font-bold text-slate-900">Quản lý sản phẩm</h1><p className="text-sm text-slate-500">Sản phẩm, danh mục, biến thể và ảnh UploadThing.</p></header>
        <form onSubmit={submit} className="space-y-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">{editing ? "Chỉnh sửa sản phẩm" : "Thêm sản phẩm"}</h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
            {[['name', 'Tên sản phẩm', 'text'], ['slug', 'Slug', 'text'], ['sku', 'SKU', 'text'], ['unitLabel', 'Đơn vị', 'text'], ['price', 'Giá', 'number'], ['compareAtPrice', 'Giá so sánh', 'number']].map(([key, label, type]) => <label key={key} className="text-sm font-medium">{label}<input required={key === 'name' || key === 'slug' || key === 'price'} min={type === 'number' ? 0 : undefined} type={type} className={field} value={String(form[key as keyof typeof form])} onChange={e => set(key, type === 'number' && key === 'price' ? Number(e.target.value) : e.target.value)} /></label>)}
            <label className="text-sm font-medium">Tồn kho<select className={field} value={form.stockStatus} onChange={e => set('stockStatus', e.target.value)}><option value="in_stock">Còn hàng</option><option value="out_of_stock">Hết hàng</option></select></label><label className="text-sm font-medium">Trạng thái<select className={field} value={form.status} onChange={e => set('status', e.target.value)}><option value="active">Hiển thị</option><option value="draft">Bản nháp</option></select></label></div>
            <div className="grid gap-4 md:grid-cols-2">{[['shortDescription', 'Mô tả ngắn'], ['description', 'Mô tả đầy đủ'], ['usageGuide', 'Hướng dẫn sử dụng'], ['preservationGuide', 'Hướng dẫn bảo quản']].map(([key, label]) => <label key={key} className="text-sm font-medium">{label}<textarea className={`${field} min-h-24`} value={String(form[key as keyof typeof form])} onChange={e => set(key, e.target.value)} /></label>)}</div>
            <fieldset><legend className="mb-2 text-sm font-bold">Danh mục</legend><div className="flex flex-wrap gap-3">{categories.map(c => <label key={c.id} className="rounded-lg border px-3 py-2 text-sm"><input type="checkbox" className="mr-2" checked={form.categoryIds.includes(c.id)} onChange={e => set('categoryIds', e.target.checked ? [...form.categoryIds, c.id] : form.categoryIds.filter(id => id !== c.id))} />{c.name}</label>)}</div></fieldset>
            <fieldset><legend className="mb-2 text-sm font-bold">Nhãn</legend><div className="flex flex-wrap gap-4">{[['isFeatured', 'Nổi bật'], ['isOnSale', 'Khuyến mãi'], ['isBestSeller', 'Bán chạy'], ['isNew', 'Mới']].map(([key, label]) => <label key={key} className="text-sm"><input type="checkbox" className="mr-2" checked={Boolean(form[key as keyof typeof form])} onChange={e => set(key, e.target.checked)} />{label}</label>)}</div></fieldset>
            <fieldset><legend className="mb-2 text-sm font-bold">Hình ảnh</legend><div className="mb-3 grid grid-cols-2 gap-3 sm:grid-cols-4">{form.images.map((image, i) => <div key={`${image.url}-${i}`}><img src={image.url} alt={image.alt ?? ""} className="aspect-square w-full rounded-lg object-cover" /><input className={field} placeholder="Alt" value={image.alt ?? ""} onChange={e => set('images', form.images.map((x, j) => j === i ? { ...x, alt: e.target.value } : x))} /><button type="button" className="mt-1 text-xs text-red-600" onClick={() => set('images', form.images.filter((_, j) => j !== i).map((x, j) => ({ ...x, position: j })))}>Gỡ</button></div>)}</div><UploadDropzone endpoint="adminImage" onClientUploadComplete={files => set('images', [...form.images, ...files.map((x, i) => ({ url: x.url, uploadKey: x.key, alt: form.name, position: form.images.length + i }))])} onUploadError={e => setMessage(e.message)} /></fieldset>
            <fieldset><div className="mb-2 flex justify-between"><legend className="text-sm font-bold">Biến thể</legend><button type="button" className="text-sm text-blue-600" onClick={() => set('variants', [...form.variants, { name: "", price: form.price, compareAtPrice: null, sku: "", position: form.variants.length }])}>+ Thêm biến thể</button></div>{form.variants.map((v, i) => <div key={i} className="mb-2 grid gap-2 rounded-lg bg-slate-50 p-3 md:grid-cols-5"><input required className={field} placeholder="Tên" value={v.name} onChange={e => set('variants', form.variants.map((x, j) => j === i ? { ...x, name: e.target.value } : x))} /><input required type="number" min="0" className={field} placeholder="Giá" value={v.price} onChange={e => set('variants', form.variants.map((x, j) => j === i ? { ...x, price: Number(e.target.value) } : x))} /><input type="number" min="0" className={field} placeholder="Giá so sánh" value={v.compareAtPrice ?? ""} onChange={e => set('variants', form.variants.map((x, j) => j === i ? { ...x, compareAtPrice: e.target.value === '' ? null : Number(e.target.value) } : x))} /><input className={field} placeholder="SKU" value={v.sku ?? ""} onChange={e => set('variants', form.variants.map((x, j) => j === i ? { ...x, sku: e.target.value } : x))} /><button type="button" className="text-sm text-red-600" onClick={() => set('variants', form.variants.filter((_, j) => j !== i).map((x, j) => ({ ...x, position: j })))}>Xóa</button></div>)}</fieldset>
            {message && <p className="text-sm text-shop-main">{message}</p>}<div className="flex gap-2"><button disabled={busy} className="rounded-lg bg-shop-main px-5 py-2 text-sm font-bold text-white disabled:opacity-50">{busy ? "Đang lưu..." : "Lưu sản phẩm"}</button>{editing && <button type="button" className="rounded-lg bg-slate-200 px-5 py-2 text-sm" onClick={() => { setEditing(null); setForm(empty) }}>Hủy</button>}</div></form>
        <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex flex-wrap gap-2"><input className={`${field} max-w-sm`} placeholder="Tìm sản phẩm, SKU, danh mục..." value={search} onChange={e => setSearch(e.target.value)} /><select className={`${field} w-auto`} value={sort} onChange={e => setSort(e.target.value)}><option value="createdAt">Ngày tạo</option><option value="name">Tên</option><option value="price">Giá</option><option value="status">Trạng thái</option></select><select className={`${field} w-auto`} value={direction} onChange={e => setDirection(e.target.value)}><option value="desc">Giảm</option><option value="asc">Tăng</option></select></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-slate-500"><tr><th className="p-3">Sản phẩm</th><th>Giá</th><th>Danh mục</th><th>Trạng thái</th><th></th></tr></thead><tbody>{items.map(p => <tr key={p.id} className="border-b border-slate-100"><td className="p-3"><strong>{p.name}</strong><small className="block text-slate-500">{p.sku || p.slug}</small></td><td>{p.price.toLocaleString('vi-VN')}₫</td><td>{p.categories.map(c => c.name).join(', ') || '—'}</td><td>{p.status === 'active' ? 'Hiển thị' : 'Nháp'}</td><td className="whitespace-nowrap text-right"><button className="mr-3 text-blue-600" onClick={() => edit(p)}>Sửa</button><button className="text-red-600" onClick={() => remove(p.id)}>Xóa</button></td></tr>)}</tbody></table></div><div className="mt-4 flex justify-between text-sm"><span>{meta.total} sản phẩm</span><div className="flex gap-2"><button disabled={meta.page <= 1} className="rounded border px-3 disabled:opacity-40" onClick={() => load(meta.page - 1)}>Trước</button><span>{meta.page}/{meta.pageCount}</span><button disabled={meta.page >= meta.pageCount} className="rounded border px-3 disabled:opacity-40" onClick={() => load(meta.page + 1)}>Sau</button></div></div></section></div>
}
